[RGB Backend-탁호진] Cart API #3 Cart_Update_Quantity
wecode-bootcamp-korea/45-1st-rgb-backend pull request #17
Opened 2023-05-08 06:56 UTC by Takhojin

<br />

---
<br />

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.
- 내 PR이 제품 내 어떠한 기능적인 배경/전후 맥락 가운데 개발되었나요?

장바구니 기능 중, 장바구니 수량을 조절이 필요하여 개발하게 되었습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

장바구니 안에서 같은 상품을 편하게 수량조절이 가능합니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 그리고 상세 내역을 적어주세요.

1. 장바구니에 상품 추가 기능 코드 내용 중 수정사항 

- cart 테이블에 products_id 에 unique 속성 추가
- query 문 수정하여 products_id 가 있다면 update로 값을 수정 , 없다면 insert로 값을 생성 

2. 장바구니 수량 조절 기능 추가

- 토큰으로 받은 userid 값과 req.body로 produtsid, calculation ( 수량조절 값 ) 을 받도록 설정
- calculation의 형태는 ( +1 or -1 ) 형태로 받는다.
- 쿼리문에서 수량 계산 실행하고, 그 값을 반환

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. (drag & drop 또는 첨부파일 추가)
<br />
1. 포스트맨 결과
![스크린샷 2023-05-08 오후 3 53 25](https://user-images.githubusercontent.com/125236449/236755170-4498c696-5d85-4954-aaf0-4bb2426eab3c.png)

2. table 값 결과
![스크린샷 2023-05-08 오후 3 53 25](https://user-images.githubusercontent.com/125236449/236755195-4708280b-969f-4616-a528-2623b7912928.png)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

-  DUPLICATE KEY 문구를 처음 써봤는데, UNIQUE 값을 지정하지 않는다면 실행이 되지않는다는 점을 알게되었다.
-  여러모로 cart 수량조절하는 방법에 대해 고심하게 되었는데, 어찌저찌 찾은 이 방법 말고 조금 다른 방법이 있나 알고싶다.
  <br />

2023-05-08 12:56 UTC, Takhojin commented
경훈님 열띈 수업을 해주셨는데 ... 트렌젝션 처리 듣다가 좌뇌가 스위치가 꺼졌는지... 수정사항이 반만 기억이나서... 일단 수정사항 기억나는데로 수정했는데 추가 할 작업있으면 알려주세요 ㅜㅜㅜㅜㅜㅜㅜ

2023-05-09 02:04 UTC, Kang-kyunghun requested changes

2023-05-09 02:04 UTC, Kang-kyunghun commented on src/controllers/cartsController.js
> +    const { productId } = req.params;
```suggestion
    const { cartId } = req.params;
```

2023-05-09 02:04 UTC, Kang-kyunghun commented on src/controllers/cartsController.js
> +    return res.status(201).json({ modifyQuantity });
```suggestion
    return res.status(200).json({ modifyQuantity });
```

2023-05-09 02:04 UTC, Kang-kyunghun commented on src/services/cartsService.js
> +};
```suggestion
const modifyQuantity = async (userId, cartId, quantity) => {
  const modifyQuantity = await cartsDao.modifyQuantity(
    userId,
    cartId,
    quantity
  );
  return modifyQuantity;
};
```

2023-05-09 02:04 UTC, Kang-kyunghun commented on src/routes/cartsRoute.js
> +router.patch("/:productId", checkToken, cartsController.modifyQuantity);
```suggestion
router.patch("/:cartId", checkToken, cartsController.modifyQuantity);
```

2023-05-09 02:04 UTC, Kang-kyunghun commented on src/models/cartsDao.js
> +        WHERE users_id= ? AND products_id = ?
```suggestion
        WHERE users_id= ? AND cart_id = ?
```

2023-05-09 02:04 UTC, Kang-kyunghun commented on src/models/cartsDao.js
> +      WHERE users_id = ?
```suggestion
      FROM cart 
      JOIN products ON cart.products_id = products.id 
      WHERE users_id = ?
```

2023-05-09 02:04 UTC, Kang-kyunghun commented on src/models/cartsDao.js
> +    console.log(userId);
로그 지워 주세요.

2023-05-09 07:43 UTC, merged